### ISSUE TITLE
[1.18.2] Some mod breaking texture loading.

### ISSUE THREAD

**Issue by Y1rd** [tomwmth/cit-reforged#3] opened 2024-10-31 00:19 UTC
Latest version works without any mods, but some mod in my instance is breaking and not loading the textures. At least no missing textures this time. I've narrowed it down to only my performance/visual mods.
Log (+Mod List): https://mclo.gs/3Efg52q

**Comment by tomwmth** [comment] 2024-10-31 17:47
Seems to be caused by other mods somehow forcing `ModelBakery#processLoading` to be invoked earlier than expected and before CIT Reforged ever receives an `FMLClientSetupEvent` to register available types.

Probably an easy fix by finding an event that triggers earlier than `FMLClientSetupEvent` or simply running the logic directly in the `@Mod` class constructor.

**Comment by tomwmth** [comment] 2024-10-31 18:27
Fixed in 7141191

**Closed by tomwmth** 2024-10-31 18:27 UTC
Labels: bug

**Comment by Y1rd** [comment] 2024-10-31 18:28
Thanks once again :D
